{% set name = "PyVISA-sim" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') | lower }}-{{ version }}.tar.gz
  sha256: 11b10658e2152708eeada0c86627d894c4d11484312f02d3cf385196b4bc870f

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pyvisa >=1.15.0
    - PyYAML
    - stringparser
    - typing-extensions

test:
  imports:
    - pyvisa_sim
    - pyvisa_sim.testsuite
  commands:
    - pip check
    - python -c "import pyvisa; rm = pyvisa.ResourceManager('@sim'); rm.list_resources(); inst = rm.open_resource('ASRL1::INSTR', read_termination='\n'); print(inst.query('?IDN'))"
  requires:
    - python {{ python_min }}
    - pip
    - pyvisa >=1.15.0

about:
  home: https://github.com/pyvisa/pyvisa-sim
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Simulated backend for PyVISA implementing TCPIP, GPIB, RS232, and USB resources'
  description: |
    PyVISA started as a wrapper for the NI-VISA library and therefore you need to install
    the National Instruments VISA library in your system. This works most of the time, 
    for most people. But sometimes you need to test PyVISA without the physical devices 
    or even without NI-VISA.

    Starting from version 1.6, PyVISA allows to use different backends. These backends can 
    be dynamically loaded. PyVISA-sim is one of such backends. It implements most of the 
    methods for Message Based communication (Serial/USB/GPIB/Ethernet) in a simulated 
    environment. The behaviour of simulated devices can be controlled by a simple plain 
    text configuration file.
  doc_url: https://pyvisa.readthedocs.io/projects/pyvisa-sim/en/latest/
  dev_url: https://github.com/pyvisa/pyvisa-sim

extra:
  recipe-maintainers:
    - MatthieuDartiailh
    - mtsolmn
